### ISSUE TITLE
Function to update setpoint

### ISSUE THREAD

**Issue by benjaminbartels** [brandondube/pctl#1]
How do you feel about adding a function that updates PID.Setpt?  I think it would be useful in case someone wants to write a interface for the PID stuct.

**Comment by brandondube** [comment]
I'm fairly neutral.  At the moment, the controller and filters satisfy the same interface by design:
```go
type Updater interface {
    Update(float64)
}
```

The controller has some other methods.  I made `IntegralReset` so that an accumulator in a model can be drained the same way.

Supposing that there were a method `Set(float64)` which moved the setpoint, then a user can write a Setter interface that it satisfies.  The question to me is more one of do users have a use case that needs the structural typing?  Meaning the exchange of types happens at runtime instead of compile time.  If you swapped this with another struct that had the same `Setpt` field wholesale there wouldn't be any other changes.

Can you share a short example that shows the utility?  It's really little code -- 3 lines plus a docstring -- but I want to understand the motivation better.

**Comment by benjaminbartels** [comment]
I believe I've talked myself out of it.  It would be for mocking purposes to test my own code that is leveraging a PID controller, and that alone is probably not a good enough reason.

**Comment by brandondube** [comment]
So you're saying you've got in mind something like:

```
func foo(p pidIFace) {
    p.Set(...)
```
Which you pass either a mock or the real thing?

I'm not sure mocking a PID is really worth that much time.  What it should do is well understood based on its construction (is there an integral error cap, is the derivative on the error or the input, etc) such that I would say mocking/modeling the input is the better path.

Simulink in matlab is made for this exact purpose.  There isn't anything in Go, but ControlSystems.jl in Julia does the same, too.  GNU Octave might have a simulink lookalike.  But, the simple plant model in the readme of this repo is decent for some things.  A controls textbook can give you the basic models of different devices.  Steve Brunton has some useful videos on youtube, too.
