### ISSUE TITLE
Add roadmap/objectives

### ISSUE THREAD

**Issue by soypat** [brandondube/pctl#3]
Hey! I'm interested in maybe contributing sometime in the future when I have the time. It'd be helpful to have a roadmap/goals section in the README or a CONTRIBUTING.md file. Let me know if I can help with anything!

**Comment by brandondube** [comment]
I can add something over the weekend.  As some early guidance, anything you need to implement the real-time loop in controls is generally in scope.  By that I mean filters, controllers, general estimators, and so on.  Code for DACs and ADCs is not in scope to me.  Analysis or loop design (in the sense of Bode, Nichols, and other plots) are not in scope.  I have not previously needed quaternions or other GNC flavored additional functionality.  I see no problem adding it here, as long as it has the same properties as the rest of pctl; no dependency that will grow the compiled code size beyond tinygo-friendly sizes, no allocations in the "real time" functions (alloc is OK in initialization, etc).

I would generally be fine with a "pctl/heavycompute/XXXXXX" set of packages that violate the tinygo-friendly property, but it gets tricky with go.mod.  So maybe that would want to be a separate repo, or go mod workspaces (I have not tried them yet) can make that simple.  In such a package I would still really like to see things by as dynamic allocation free as possible, so that the computation time which directly contributes to phase margin is more deterministic, and the GC is not pressured.

**Comment by brandondube** [comment]
I added a roadmap in 6a043c2d413fce572a72d30b47ea84565c955e6a ; could you look and see if this addresses your question?

**Comment by soypat** [comment]
Yes it did- thanks!
